### ISSUE TITLE
Keep long connection between client and server

### ISSUE THREAD

**Issue by nodecook-dev** [nodecook/agent#3]
Client connect server instead server connect client so that client don't need expose port

**Comment by cxw620** [comment]
Long connection will add substantial load on the main server.

BTW, I suggest gRPC bidirectional streaming instead of websocket.

**Comment by nodecook-dev** [comment]
We only need keep maximum hundreds connections, maybe that's acceptable? The benefits are some devices which don't have public ip can also join without port forward configuration. BTW, why do you think gRPC is better than websocket?

**Comment by cxw620** [comment]
> We only need keep maximum hundreds connections, maybe that's acceptable? The benefits are some devices which don't have public ip can also join without port forward configuration. BTW, why do you think gRPC is better than websocket?

It's the maintainer of `ping.pe`(with about 70 clients) who comes with such opinion. I'm not sure how much extra load one more client will add to main server and you may test it. 

gRPC is what I mainly make use of in my prod proj and it works well in such scene. However, I must admit that there may not be any outstanding advantages in terms of performance, just an alternative choice :)

BTW, since ws supports sending binary messages, you may want to avoid serializing or deserializing messages with serde_json, which may improve performance. bincode may be a good choice. See [https://david.kolo.ski/rust_serialization_benchmark/](https://david.kolo.ski/rust_serialization_benchmark/) for benchmarks result.

**Comment by nodecook-dev** [comment]
Thanks for your advice! I will check that.

**Comment by cxw620** [comment]
> Thanks for your advice! I will check that.

Crate bincode is compatible with WebAssembly; you can even directly relay the binary data returns by NCAs to users and let their browsers decode the data. It will reduce the load on the main server.
